#!/bin/bash
export NODE_ENV=production
export HOME=$OPENSHIFT_REPO_DIR

if [ -f "${OPENSHIFT_REPO_DIR}"/Gruntfile.js ]; then
    (cd "${OPENSHIFT_REPO_DIR}"; node_modules/grunt-cli/bin/grunt prod)
fi
